Drop `bool` typedef (#71)
GCC throws an error when a bool type is defined:

```
./c-shared-util.h:17:15: error: 'bool' cannot be defined via 'typedef'
   17 |   typedef int bool;
      |               ^~~~
./c-shared-util.h:17:15: note: 'bool' is a keyword with '-std=c23' onwards
```

Since bool and int don't need to be the same types at the ABI boundary
we must replace `bool` by `int` there. We can still use `true` and
`false` internally due to implicit type conversion.

Signed-off-by: Guido Günther <agx@sigxcpu.org>